# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: C. Ashwin
email: cashwn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my personal portfolio where you can view all my projects, interests and contact details. Feel free to connect with me if you want to collaborate
 in a project involving robotics preferably in the domain of control and simulation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  AshwinC313

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
